name: '🚔'
on: [ push, pull_request ]
jobs:
  test:
    if: startsWith(github.ref, 'refs/tags/v') == false
    runs-on: ubuntu-24.04
    steps:

      - uses: actions/checkout@v5
        with:
          fetch-depth: 0

      - name: 'Install devbox'
        uses: jetify-com/devbox-install-action@v0.13.0

      - name: 'Run tests'
        run: |
          devbox run --pure test
